name: Mirror to Tangled

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Start SSH agent and add key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.TANGLED_SSH_KEY }}

      - name: Trust Tangled host key
        run: ssh-keyscan tangled.sh >> ~/.ssh/known_hosts

      - name: Push to Tangled
        run: |
          git remote add tangled git@tangled.sh:jaydip.me/moocup
          git push tangled main:from-github